config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  post 'contact_form' => 'welcome#contact_form'

    get '*path' => redirect('/')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car_picture.rb
class CarPicture < ApplicationRecord

	validates :car_id, presence: true
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :tel,       :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      :attachment => true

  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Q&A SL Autos",
      :to => "bartdn183@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact_form
     if !params[:name].nil? && !params[:email].nil? && !params[:email].nil? && !params[:message].nil? && !params[:tel].nil? 
	  	c = ContactForm.new(:name => params[:name], :email => params[:email], :message => params[:message], :tel => params[:tel])
	  	c.deliver
  	  redirect_to root_path
  	 else
  	 	redirect_to root_path

  	 end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarSaleApp</title>
    <%= csrf_meta_tags %>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">  

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body id="page-top" class="index">
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/welcome/_contact.html.erb
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading"><span style="padding: 6px 12px; background: rgba(255,255,255, 0.9); border-radius: 13px; color: black; font-weight: 400;">Contact Us</span></h2>
                <h3 class="section-subheading text-muted"></h3>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <%= form_with url: contact_form_path, method: :post, novalidate: "novalidate" do |form| %>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <%= form.text_field :name, class: "form-control", placeholder: "Your Name *", id: "name", required: true %>
                            </div>
                            <div class="form-group">
                                <%= form.text_field :email, class: "form-control", placeholder: "Your Email *", id: "email", required: true %>
                            </div>
                            <div class="form-group">
                                <%= form.text_field :tel, class: "form-control", placeholder: "Your Phone *", id: "phone", required: true %>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                            <%= form.text_area :message, class: "form-control", placeholder: "Your Message *", id: "message", required: true %>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-lg-12 text-center">
                            
                              <%= form.submit "Send Message", class: "btn btn-xl" %>
                        </div>
                    </div>
                <!-- </form> -->
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/welcome/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <span class="copyright">Copyright &copy; SL Autos 2017</span>
            </div>
            <div class="col-md-4">
                <ul class="list-inline social-buttons">
                    <li><a href="#"><i class="fa fa-twitter"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-facebook"></i></a>
                    </li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a>
                    </li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-inline quicklinks">
                    <li><a href="#">Privacy Policy</a>
                    </li>
                    <li><a href="#">Terms of Use</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

app/views/welcome/_header.html.erb
<header>
    <div class="container">
        <div class="intro-text">
            <div class="intro-lead-in">Welcome To <span style="color: #b30000">SL</span> Autos!</div>
            <div class="intro-heading">Servicio Espacializado</div>
            <a href="#services" class="page-scroll btn btn-xl">Tell Me More</a>
        </div>
    </div>
</header>

app/views/welcome/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
            </button>
            <div style="margin-top: -13px;">
            <%= link_to "#page-top", class: "navbar-brand page-scroll" do %>
                
            <%= image_tag "logo.jpg", size: 45, style: "display:inline;", class: "img-rounded" %> <span style="color: #e60000; font-size: 40px; font-family: 'Tangerine', cursive; font-weight: 700;">SL</span><span style="color: white; font-size: 30px;font-family: 'Tangerine', cursive; font-weight: 700;"> Autos</span> <% end %>
               
            </div>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <%= link_to "", "#page-top" %>
                </li>
                <li>
                    <%= link_to "Services", "#services", class: "page-scroll" %>
                </li>
                <li>
                    <%= link_to "Sell", "#" %>
                </li>
                <li>
                    <%= link_to "Buy", "#" %>
                </li>
                <li>
                    <%= link_to "Team", "#team", class: "page-scroll" %>
                </li>
                <li>
                    <%= link_to "Contact", "#contact", class: "page-scroll" %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/welcome/_services.html.erb
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Services</h2>
                <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-car fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="service-heading">Cars</h4>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-laptop fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="service-heading">Responsive Design</h4>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fa fa-circle fa-stack-2x text-primary"></i>
                    <i class="fa fa-lock fa-stack-1x fa-inverse"></i>
                </span>
                <h4 class="service-heading">Web Security</h4>
                <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minima maxime quam architecto quo inventore harum ex magni, dicta impedit.</p>
            </div>
        </div>
    </div>
</section>

app/views/welcome/_team.html.erb
<section id="team" class="bg-light-gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Our Amazing Team</h2>
                <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <div class="team-member">
                    <%= image_tag "team/1.jpg", class: "img-responsive img-circle" %>
                    <h4>Kay Garland</h4>
                    <p class="text-muted">Lead Designer</p>
                    <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="team-member">
                    <%= image_tag "team/2.jpg", class: "img-responsive img-circle" %>
                    <h4>Larry Parker</h4>
                    <p class="text-muted">Lead Marketer</p>
                    <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="team-member">
                    <%= image_tag "team/3.jpg", class: "img-responsive img-circle" %>
                    <h4>Diana Pertersen</h4>
                    <p class="text-muted">Lead Developer</p>
                    <ul class="list-inline social-buttons">
                        <li><a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <p class="large text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut eaque, laboriosam veritatis, quos non quis ad perspiciatis, totam corporis ea, alias ut unde.</p>
            </div>
        </div>
    </div>
</section>

app/views/welcome/index.html.erb
<%= render 'navbar' %>

<%= render 'header' %>

<%= render 'services' %>

<%= render 'team' %>

<%= render 'contact' %>

<%= render 'footer' %>